format = """
$directory$cmd_duration
$character"""

add_newline = true
command_timeout = 750

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold #6C8EAD"
truncation_length = 3
truncate_to_repo = false
read_only = " 󰌾"
read_only_style = "#C17D61"

[cmd_duration]
format = "[$duration]($style) "
min_time = 5000
style = "#C4A46B"

[character]
success_symbol = "[❯](#81A1C1)"
error_symbol = "[❯](#BF616A)"
vimcmd_symbol = "[❮](#A3BE8C)"

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[package]
disabled = true

[hostname]
disabled = true

[username]
disabled = true
