local map = vim.keymap.set

map('n', '<Esc>', '<cmd>nohlsearch<CR>', { desc = 'Clear search highlight' })
map('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Leave terminal mode' })

map('n', '<C-h>', '<C-w><C-h>', { desc = 'Move to left window' })
map('n', '<C-j>', '<C-w><C-j>', { desc = 'Move to lower window' })
map('n', '<C-k>', '<C-w><C-k>', { desc = 'Move to upper window' })
map('n', '<C-l>', '<C-w><C-l>', { desc = 'Move to right window' })

map('n', '<leader>wv', '<C-w>v', { desc = 'Split right' })
map('n', '<leader>ws', '<C-w>s', { desc = 'Split below' })
map('n', '<leader>wq', '<C-w>q', { desc = 'Close window' })
map('n', '<leader>wo', '<C-w>o', { desc = 'Only window' })
map('n', '<leader>w=', '<C-w>=', { desc = 'Balance windows' })

map('n', '<leader><space>', function()
  Snacks.picker.smart()
end, { desc = 'Smart find files' })
map('n', '<leader>,', function()
  Snacks.picker.buffers()
end, { desc = 'Buffers' })
map('n', '<leader>/', function()
  Snacks.picker.grep()
end, { desc = 'Grep in project' })
map('n', '<leader>:', function()
  Snacks.picker.command_history()
end, { desc = 'Command history' })
map('n', '<leader>e', function()
  Snacks.explorer()
end, { desc = 'File explorer' })
map('n', '<leader>ff', function()
  Snacks.picker.files()
end, { desc = 'Find files' })
map('n', '<leader>fg', function()
  Snacks.picker.git_files()
end, { desc = 'Find git files' })
map('n', '<leader>fr', function()
  Snacks.picker.recent()
end, { desc = 'Recent files' })
map('n', '<leader>sd', function()
  Snacks.picker.diagnostics()
end, { desc = 'Search diagnostics' })
map('n', '<leader>sg', function()
  Snacks.picker.grep()
end, { desc = 'Search by grep' })
map('n', '<leader>sh', function()
  Snacks.picker.help()
end, { desc = 'Search help' })
map('n', '<leader>sk', function()
  Snacks.picker.keymaps()
end, { desc = 'Search keymaps' })

map('n', '<leader>gg', function()
  Snacks.lazygit()
end, { desc = 'LazyGit' })

map({ 'n', 'x' }, '<leader>cf', function()
  require('config.format').format()
end, { desc = 'Format buffer' })

map('n', ']d', vim.diagnostic.goto_next, { desc = 'Next diagnostic' })
map('n', '[d', vim.diagnostic.goto_prev, { desc = 'Previous diagnostic' })
map('n', '<leader>cd', vim.diagnostic.open_float, { desc = 'Line diagnostics' })
map('n', '<leader>cl', vim.diagnostic.setloclist, { desc = 'Diagnostics to location list' })

map('n', '<F5>', function()
  require('dap').continue()
end, { desc = 'Debug continue' })
map('n', '<F10>', function()
  require('dap').step_over()
end, { desc = 'Debug step over' })
map('n', '<F11>', function()
  require('dap').step_into()
end, { desc = 'Debug step into' })
map('n', '<S-F11>', function()
  require('dap').step_out()
end, { desc = 'Debug step out' })
map('n', '<leader>db', function()
  require('dap').toggle_breakpoint()
end, { desc = 'Toggle breakpoint' })
map('n', '<leader>dB', function()
  require('dap').set_breakpoint(vim.fn.input 'Breakpoint condition: ')
end, { desc = 'Conditional breakpoint' })
map('n', '<leader>du', function()
  require('dapui').toggle()
end, { desc = 'Toggle debug UI' })
map('n', '<leader>dr', function()
  require('dap').repl.toggle()
end, { desc = 'Toggle debug REPL' })
